id: P4F3A449A
initial_creation_type: input
source_metadata:
  title: Mipham Rinpoche Series
  language: zh
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    7f4f17f077fb4ca78e3982b84f4f59fb:
      title: Advice for Beginners
      parent: Advice
    ab0c8a1229aa473f86b7ed8f175aaf0e:
      title: Advice to Jigme Tenpe Nyima
      parent: Advice
    25a716b0285e451aab8431e63a59308b:
      title: Essence of the 84000 Approaches to the Dharma
      parent: Advice
    25765e461500488d8f01c7cd7545db26:
      title: How to Cultivate Concentration
      parent: Advice
    153a6b85a50040aeadae624fb06b04bf:
      title: Profound Instruction on Śamatha
      parent: Advice
    25f8540f93984450be916295d8062581:
      title: Satirical Advice for the Four Schools
      parent: Advice
    9634125e6610467c84d5997d62bbcb8d:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    312811ab625d433d882a290c6a76e6c3:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    8d207698104f42d39420d696e4d09624:
      title: The Perfect Equality of the Dharmadhātu
      parent: Advice
    7559e20547c9455591757aa57c046e02:
      title: A Brief Prayer for Summoning Prosperity
      parent: Aspiration Prayers
    65a7552a758d49ae9d63d127a406f4d9:
      title: Aspiration for the Four Activities
      parent: Aspiration Prayers
    935250de93724b00819cbf86732947c8:
      title: Light Offering Prayer
      parent: Aspiration Prayers
    3cc4c6938b6c4bb08ede4a6c1be718fb:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers
    53687c7b124e4fa68443e485a259cdc0:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Aspiration Prayers
    586b7b52f3324c898d30b4aad33c690d:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
    acb3b02b951548c680f0e098a4399177:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Aspiration Prayers
    a20a57ae57424a1e853f77c8dcb7fc57:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    cc33458de91d435cb54a5be7fe8f5508:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Averting Obstacles
    18e6bc2123b14a38be59fcd88f8c06f8:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      parent: Benedictory Verses
    a1872fc2ad2e4d04a426c702029a6663:
      title: Benedictory Verses for White Lotus
      parent: Benedictory Verses
    e0070c98db564d80ac98904b2782d037:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Buddhist Philosophy
    cf23f939938e4d52b4ccd84005ed1f74:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
    bd4440cd8f574fc082ab0144b9bc04e5:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Buddhist Philosophy
    a7491ca36c834655afb65433d5b1c022:
      title: Profound Instruction on the View of the Middle Way
      parent: Buddhist Philosophy
    6e3ca149fe3b4be19d4579ada420beb1:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Buddhist Philosophy
    dd63947caf194637a6b20bb5ba761487:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Buddhist Philosophy
    7ceecbdb9c1f46bab2cd78d4584fa16d:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Buddhist Philosophy
    0517b42b73ec48fb8e960d975634a4f6:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Buddhist Philosophy
    96fa250591144d1e99f8306e51b03e8a:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    d5f2dc88b8a14a43b8be8f0a83173107:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Dharma Protectors
    5e2c6a09c12f4403beac6f2779ec30d4:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Dharma Protectors
    aa96787d70ba4ceb9be5979c236b3899:
      title: Brief Offering Prayer to Za Rāhula
      parent: Dharma Protectors
    e8501781cc3543e293392fcbc05bb929:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Dharma Protectors
    b8cccfc1d7804342bbf923186bd2b3fa:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Dharma Protectors
    32221452f6474275bc7775c65ddfc483:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Dzogchen
    1f723b9a75594d8887c9579f260733c1:
      title: Pith Instruction on the Three Crucial Statements
      parent: Dzogchen
    bfbf78ed7a334735b277ad5115dc9812:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    4e9ed56c7ff44411b6b5ba04134ef1fd:
      title: The Essence of Mind
      parent: Dzogchen
    cb24406adff94f78aac42a3cd6e27492:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Dzogchen
    320d83292ecd44e995e69de7330fd940:
      title: The Key Points of Trekchö
      parent: Dzogchen
    84499679ccd3400899ca447da109df99:
      title: The Nature of Mind
      parent: Dzogchen
    57e22b0a431b4873806eb4bad5e0ae2a:
      title: Brief Gesar Windhorse Invocation
      parent: Gesar
    338ea1e408b549bab3d59d04097905ca:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    d216edebf095418faed37e90ef9ce136:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Gesar
    0dbc9f17e63e49d791f30b4d6b6a46a7:
      title: Prayer to Gesar
      parent: Gesar
    c2ab3bff07e54195a49ca4860ebf6fa2:
      title: Short Windhorse Prayer to Gesar
      parent: Gesar
    0a7cb168f6f34c92a01fb576654e9be1:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Gesar
    04d032e341234d5e8f2f1c9c67de4db4:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Gesar
    5320e6bec6134c2ca7edf42f743aa6b2:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Gesar
    0d1d1cdd78c54915a80504aa92b47475:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Gesar
    61d9afd72a704d9ea8b574fdca8b2336:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    b63e60c45492436db170c1c03b1920d3:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    51e04926598b45c0a0812c08aa2737bf:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Guru Yoga
    8041bdb415f34b89b555b7595f94db39:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Guru Yoga
    bc9262f1f2df4b519dc0cceef89e3baa:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    4f0adbff33b14c578f350218d9fa67bc:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    c95ef145050147dd973217882a3f50f3:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Guru Yoga
    5e89acd03d544b9d8687f20fe84c1acb:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    db5a90a3ab3b4404adc23686fdcfc34b:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    f59acc4b855e40ffa45adf09434af4c7:
      title: Short Torma Offering to Kurukullā
      parent: Kurukullā
    69b6e5f5da494c54902dd94b0fb68a76:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    104286f57e5c46ed87515a4b86ead6d7:
      title: Brief Dzogchen Lineage Prayer
      parent: Lineage Prayers
    c63ac08807454ee6bd43fe1622d25e2e:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    8b907f88ac94441cb39697d1df4ee892:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    fe3636a0987846f495d4f35a1c47e3b9:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Longevity
    77301aeca8f940279f332b839e8f8231:
      title: Brief Windhorse Invocation
      parent: Lungta
    3e5eb1d410724d938dfb8a322a370f05:
      title: Daily Lungta Recitation
      parent: Lungta
    179ea21026884e589cf32019bdc5a4dd:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Lungta
    b8631d6717214103a6c32f8ca909e421:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    26528e53edb1497eb87377d7d2b7e486:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    de01a51909504148a100947e97212253:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Offering
    5603b90f05c14304b9dbc973cd188c4b:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    c05db92974ff4070b968eac7009e6a5a:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Praise
    2dd9ad5fbb504792ad8a96859d13808b:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    971b1c6a448e47c0b24c3dac77a9e69f:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    6a972abfcdce42bbb1b70f1820377b7e:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Prayers
    8fbed13b3e494fab8afa36453bfe18eb:
      title: Prayer to Akṣobhya
      parent: Prayers
    770521b81a4745278d4178d20d41c76a:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
    057836bcea464feea8a84470d0584418:
      title: Three Prayers from the Earth Pig Year
      parent: Prayers
    868f900feb8143febb5140b75396f208:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    72d7e90bfa164ddbba8518057cae5d9f:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Prayers to Guru Rinpoche
    74b7cbfc0fc5404fafea0f8f0ba545dd:
      title: Recollecting the Deeds of The Tenth Days
      parent: Prayers to Guru Rinpoche
    0b72b9c90713420c92308756070e1755:
      title: The Prayer which is the Source of All True Realization
      parent: Prayers to Guru Rinpoche
    af64e0bf00704cd5a78a5c5e84ecc422:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Prayers to Mañjuśrī
    03ff43ddecc94a83bb17fd48b98587f7:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Prayers to Mañjuśrī
    6c22f09d684540e985774183902e83aa:
      title: In Praise of the Protector Mañjughoṣa
      parent: Prayers to Mañjuśrī
    52bc94b025ca48dabda1f69393f61f82:
      title: Prayer to Mañjuśrī
      parent: Prayers to Mañjuśrī
    9f918460168f46a78115bed00dcfef67:
      title: Prayer to the Sovereign of Dharma and Retinue
      parent: Prayers to Śākyamuni
    0998d3a538b74a47bb659f33fbfd1fa0:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
    fb26f7c18f5d4b409cc55498dbf41fff:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: Preliminary Practice
    cd1666f5dcb64d158898b07e2fb49533:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    d085a7adc92f40b9820f0925955876a8:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    81903060ae8e41298ed2b959762e85e0:
      title: A Sādhana of Sitātapatrā
      parent: Sādhanas
    00e95c45e74f4415b79f43f603f0b9d0:
      title: A Sādhana of White Sarasvatī
      parent: Sādhanas
    5d3e843052f4464ab0bc2f071e46f824:
      title: Acala Sādhana
      parent: Sādhanas
    ba1bd998cc654f81892bcbf680337ec5:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
    040a43b47fde442aaaf22d8c5d29a890:
      title: Sādhana of Mārīcī
      parent: Sādhanas
    d6c29319aaf545008106a29d1348e731:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    abdd30bf9807435b9c8a317c396e172d:
      title: Brief Sang Offering
      parent: Sang Offering
    ded221321ca9423bab26f678c19acb47:
      title: Brief Sang Offering to Purify Contamination
      parent: Sang Offering
    515e339239454bf992c0e282165b6075:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Saving Lives
    c1d804a38884401195d5b98ad199515c:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    320d28dba72848d18529cbefc83adfa1:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    93ef4fcd14e24f2996f5716109e03f33:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Tārā
    f32c6e976ac94459ae2f91a744c39145:
      title: Outline of the Ten Royal Sūtras
      parent: Topical Outlines
    dd032682168d4a03b9aa77a354290c12:
      title: Concise Tsok Feast
      parent: Tsok
    47e8644ff3c14e1e9c5cd00f344ecfc6:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Tsok
    2e727a82664e4c71b0539d3f5a4eb5fc:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Vajrasattva
created_at: '2022-03-01T00:57:12.463510'
last_modified_at: '2022-03-01T00:57:12.463513'
